const myfiles =[
    {
        movie:"/src/assets/movie/Cinema.mp4",
        name:"Cinema",
        path:""
    },
    {
        movie:"/src/assets/movie/ThronOfliberty.mp4",
        name:"ThronOfliberty",
        path:""
    },
    {
        movie:"/src/assets/movie/Olcha.mp4",
        name:"Olcha",
        path:""
    },
    {
        movie:"/src/assets/movie/ZoneBusinnes.mp4",
        name:"ZoneBusinnes",
        path:""
    },
    {
        movie:"/src/assets/movie/RoyalX.mp4",
        name:"RoyalX",
        path:""
    },
    {
        movie:"/src/assets/movie/MaxWay.mp4",
        name:"MaxWay",
        path:""
    },
    {
        movie:"/src/assets/movie/Crayson.mp4",
        name:"Crayson",
        path:""
    },
    {
        movie:"/src/assets/movie/Lineage2.mp4",
        name:"Lineage2",
        path:""
    },
    {
        movie:"/src/assets/movie/Totembo.mp4",
        name:"Totembo",
        path:""
    },
    {
        movie:"/src/assets/movie/Browsers.mp4",
        name:"Browsers",
        path:""
    },
    {
        movie:"/src/assets/movie/Food.mp4",
        name:"Food",
        path:""
    },
    {
        movie:"/src/assets/movie/Amazon.mp4",
        name:"Amazon",
        path:""
    },
]
export default myfiles